### ISSUE TITLE
open korean text에서 user-dic문의

### ISSUE THREAD

**Issue by renuevo** [open-korean-text/elasticsearch-analysis-openkoreantext#13]
user-dic에서 Noun외의 Verb같은 사전도 추가 가능 한지 궁금합니다
또한 색인시 Noun과 Verb과 같은 type을 구분하여 색인 가능 한지도 문의 드립니다.
open-korean-text-2.1.0.jar의 내부 util에 사전 파일을 바꿔도 업데이트가 안되는 것 같은데
내부 default 사전은 어느 사전을 사용하고 있는지 궁금합니다

**Comment by keepcosmos** [comment]
현재는 Noun만 가능합니다. 

사용하는 사전은, open-korean-text 프로젝트에 정의된 사전을 사용합니다.

사전은 해당 프로젝트에서 자체적으로 만들고 있습니다. 
https://github.com/open-korean-text/open-korean-text/tree/master/src/main/resources/org/openkoreantext/processor/util
