### ISSUE TITLE
오타가 있습니다.

### ISSUE THREAD

**Issue by pokev25** [open-korean-text/elasticsearch-analysis-openkoreantext#2]
'descriptor' 에

'name': 'elasticserach-analysis-openkoreantext'

elasticsearch 인데 elasticserach로 되어 있네요.

그리고 5.4.1 버전대응은 build.gradle 의 버전명만 올려서 빌드 해서 사용하면 되는건가요?

**Comment by keepcosmos** [comment]
리포트 감사합니다 :) 오타는 수정해서 올렸어요~

5.4.1 버젼도 업로드 하였습니다.
https://github.com/open-korean-text/elasticsearch-analysis-openkoreantext/releases/download/5.4.1.2/elasticsearch-analysis-openkoreantext-5.4.1.2-plugin.zip

직접 커스텀 하실경우, build.gradle 파일에서 버젼 바꿔주시고, `makePluginDescriptor` 테스크에서 `elasticsearchVersion` 을 수정한 후 build 하시면, `/build/tmp/plugin`에 zip 파일이 생성되어 있을거에요.

**Comment by pokev25** [comment]
/build/distributions 에 있는거 아닌가요?
