### ISSUE TITLE
Publish Plugin to Maven Repository

### ISSUE THREAD

**Issue by jaemoore** [open-korean-text/elasticsearch-analysis-openkoreantext#4]
Currently it's extremely difficult to include the plugin in a maven project.

Would you be able to publish this to maven repository in addition to github?

Currently we include other plugins published on maven in our project through this format:

open-korean-text:elasticssearch-analysis-openkoreantext:${elasticsearch.version}.2

Which bin/elasticsearch-plugin install will look at maven for.

**Comment by hohyon-ryu** [comment]
@keepcosmos Can you register and publish this in the public maven repository?

**Comment by keepcosmos** [comment]
@jaemoore @nlpenguin Sure, I will

**Comment by keepcosmos** [comment]
@jaemoore 
Thanks for waiting, Check https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22elasticsearch-analysis-openkoreantext%22

**Comment by jaemoore** [comment]
@keepcosmos  Thanks!
