### ISSUE TITLE
custom analyzer 적용에 대한 질문입니다.

### ISSUE THREAD

**Issue by pokev25** [open-korean-text/elasticsearch-analysis-openkoreantext#5]
analyzer 테스트를 위해서 readme에 있는 내용대로 필터를 적용했습니다.
kibana에서 다음의 명령으로 테스트를 진행했습니다.

```
POST openpedia/_analyze
{
  "char_filter" : ["openkoreantext-normalizer"],
  "tokenizer": "openkoreantext-tokenizer",
  "filter":  [ "openkoreantext-stemmer", "openkoreantext-redundant-filter", "classic-filter", "length-filter", "lowcase" ],
  "text":"아버지가방에들어가신다."
}
```

classic-filter, length-filer,lowcase를 찾을 수 없다고 나옵니다.

"classic", "length", "lowercase" 로 지정하니 동작합니다.

플러그인 내부에서 사용하는 필터명과 커스텀 분석기 적용시의 필터명이 다른가요?

**Comment by keepcosmos** [comment]
아하! 실제 필터 이름은 "classic", "length", "lowercase" 가 맞습니다. README 수정하였어요.
감사합니다 👍
