### ISSUE TITLE
es 5.5.0 이 배포 되었습니다.

### ISSUE THREAD

**Issue by pokev25** [open-korean-text/elasticsearch-analysis-openkoreantext#7]
버전만 바꿔서 빌드 해보니 test에서 걸리네요.

뭔가 바뀐것이 있는듯 합니다. 

아..그리고  open-korean-text 도 2.0.4로 버전이 올라갔네요 ^^

**Comment by keepcosmos** [comment]
리포팅 감사합니다. 5.5.0 으로 올라가면서 ESTest 모듈 쪽 디펜던시가 변경된듯 보이네요. 확인 후 업데이트 하겠습니다 :+1:

**Comment by keepcosmos** [comment]
@pokev25 5.5.0 지원버젼 플러그인 파일 올렸습니다. 엘라스틱서치 버젼 릴리즈 사이클이 엄청 빠르네요 ㅎㅎ

open-korean-text는 지금 테스트 커버리지 올리는 작업을 활발히 하는 중인거 같네요. https://github.com/open-korean-text/open-korean-text/issues/30 이 작업이 마무리되고 안정되면 올리도록 하겠습니다.
