### ISSUE TITLE
How can I use this for elastic search version 2.3.4

### ISSUE THREAD

**Issue by ashmanmode** [open-korean-text/elasticsearch-analysis-openkoreantext#9]
When using this on elasticsearch 2.3.4 version, I m getting the below error for tokenizer query
PUT openkorean_sample/_settings
{
  "settings": {
    "index": {
      "analysis": {
        "analyzer": {
          "my_icu_analyzer": {
            "tokenizer": "openkoreantext-tokenizer"
          }
        }
      }
    }
  }
}

POST  /openkorean_sample/_analyze
{
  "analyzer": "my_icu_analyzer",
  "text" : "한국어를 처리하는 예시입니닼ㅋㅋ"
}

Error : 
{
   "error": {
      "root_cause": [
         {
            "type": "no_shard_available_action_exception",
            "reason": "No shard available for [org.elasticsearch.action.admin.indices.analyze.AnalyzeRequest@164c06a8]"
         }
      ],
      "type": "no_shard_available_action_exception",
      "reason": "No shard available for [org.elasticsearch.action.admin.indices.analyze.AnalyzeRequest@164c06a8]"
   },
   "status": 503
}

**Comment by keepcosmos** [comment]
This plugin does not support ES 2.x,
If you need plugin for 2.x, please check https://github.com/open-korean-text/open-korean-text-elastic-search or https://github.com/jobplanet/elasticsearch-twitter-korean
